In [1]:
import numpy as np
array = np.array([11, 22, 33, 44, 55])
print("Original array:", array)
print("Addition of 2:", array + 2)
print("Multiplication by 3:", array * 3)
print("Division by 2:", array / 2)

Original array: [11 22 33 44 55]
Addition of 2: [13 24 35 46 57]
Multiplication by 3: [ 33  66  99 132 165]
Division by 2: [ 5.5 11.  16.5 22.  27.5]


In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("array:", arr)
print("Reversed:", arr[::-1])

array: [1 2 3 6 4 5]
Reversed: [5 4 6 3 2 1]


In [3]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
print("Most frequent value:", most_frequent)
print("Indices:", np.where(x == most_frequent)[0])

Most frequent value: 1
Indices: [0 5 7 8 9]


In [4]:
y = np.array([1,1,1,2,3,4,2,4,3,3,])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
print("Most frequent value:", most_frequent)
print("Indices:", np.where(y == most_frequent)[0])

Most frequent value: 1
Indices: [0 1 2]


In [5]:
arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print("Accessing 1st row, 2nd column:", arr[0, 1])
print("Accessing 3rd row, 1st column:", arr[2, 0])

Accessing 1st row, 2nd column: 20
Accessing 3rd row, 1st column: 70


In [6]:
Vish = np.linspace(10, 100, 25)

print("Array:", Vish)
print("Dimensions:", Vish.ndim)
print("Shape:", Vish.shape)
print("Total elements:", Vish.size)
print("Data type:", Vish.dtype)
print("Total bytes:", Vish.nbytes)

Vish_transpose = Vish.reshape(25, 1)

print("Transpose using reshape() : ")
print(Vish_transpose)

print("Doable using T attribute?", Vish.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape() : 
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Doable using T attribute? [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
ucs420_Vish = np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]])

print("Original array:")
print(ucs420_Vish)

print("Mean:", np.mean(ucs420_Vish))
print("Median:", np.median(ucs420_Vish))
print("Maximum:", np.max(ucs420_Vish))
print("Minimum:", np.min(ucs420_Vish))
print("Unique elements:", np.unique(ucs420_Vish))
reshaped_ucs420_Vish = ucs420_Vish.reshape(4, 3)

print("Reshaped array:")
print(reshaped_ucs420_Vish)
resized_ucs420_Vish = np.resize(ucs420_Vish, (2, 3))
print("Resized array:")
print(resized_ucs420_Vish)

Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
